  version: "3"
  services:
    java-server:
      build: .
      image: java-custom-server
      restart: always
      ports:
        - "8081:8080"
      depends_on:
        - mysqldb

    mysqldb:
      image: mysql:5.6
      restart: always
      ports:
        - "3307:3306"
      volumes:
        - ./db:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=${PASSWORD}
        - MYSQL_DATABASE=${DATA_BASE}

